### ISSUE TITLE
Android Studio Chipmunk | 2021.2.1 Patch 1适配

### ISSUE THREAD

**Issue by urartu** [azhon/TODO-MVVM#15]
[更新开发环境到Android] Studio Chipmunk | 2021.2.1 Patch 1，原来代码出现问题。在viewmodel中使用LoadingDialog会报错。
java.lang.RuntimeException: view must have a tag。
![1](https://user-images.githubusercontent.com/7639028/170961612-e0414259-2652-4508-94ca-65657908a9bd.png)
![2](https://user-images.githubusercontent.com/7639028/170961640-ca8e19d4-156a-4986-bec2-099694039bc1.png)

**Comment by azhon** [comment]
未复现
Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 19, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
