### ISSUE TITLE
这个AS版本这么高的吗

### ISSUE THREAD

**Issue by LaelLuo** [azhon/TODO-MVVM#2]
😂3.5 or later

**Comment by azhon** [comment]
是的，我使用的是当时最新的预览版

**Comment by Ashion-AS** [comment]
3.4.1报找不到BR文件，也不能编译，需要配置下什么吗？

**Comment by azhon** [comment]
可以试下升级AS，或者你把问题搜索一下

**Comment by Ashion-AS** [comment]
公司还是得用稳定版，百度了试了很多没有解决……
 classpath 'com.android.tools.build:gradle:3.4.1'
distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
我就改了这2处……

**Comment by azhon** [comment]
那你可以自己创建个项目，然后把我这边的类东西复制过去，看行不行




------------------ 原始邮件 ------------------
发件人: "Ashion-AS"<notifications@github.com>; 
发送时间: 2019年7月2日(星期二) 下午3:09
收件人: "azhon/TODO-MVVM"<TODO-MVVM@noreply.github.com>; 
抄送: "阿钟"<958460248@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [azhon/TODO-MVVM] 这个AS版本这么高的吗 (#2)




公司还是得用稳定版，百度了试了很多没有解决……
 classpath 'com.android.tools.build:gradle:3.4.1'
 distributionUrl=https://services.gradle.org/distributions/gradle-5.1.1-all.zip
 我就改了这2处……

**Comment by Ashion-AS** [comment]
问题解决了，发现还是第一个issue的问题，把xml中的全部中文定义到value string 中可以了

**Comment by azhon** [comment]
这么神奇的吗

**Comment by Ashion-AS** [comment]
问了下别人，里面不能写中文……估计你用的很高的版本 支持，3.X好像都不行
