### ISSUE TITLE
Caused by: org.apache.xerces.impl.io.MalformedByteSequenceException: Invalid byte 3 of 3-byte UTF-8 sequence.

### ISSUE THREAD

**Issue by LaelLuo** [azhon/TODO-MVVM#3]
错误: 找不到符号
符号:   类 BR
位置: 程序包 com.azhon.mvvm
![image](https://user-images.githubusercontent.com/26056971/55700023-38be3480-5a00-11e9-8223-2e0694ce15a9.png)

**Comment by azhon** [comment]
应该是dataBinding编译的问题，清缓存重启AS或者使用AS3.5或更高版本；
或者把布局文件的字符串全部输入过一遍好像也可以。

**Comment by LaelLuo** [comment]
我现在用的就是
Android Studio 3.5 Canary 10
Build #AI-191.6183.62.35.5416148, built on March 29, 2019
JRE: 1.8.0_202-release-1483-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by azhon** [comment]
那应该就是DataBinding字符串编译问题了，[这个可以解决](https://blog.csdn.net/sunsteam/article/details/76066595)

**Comment by songsongtao** [comment]
建议把`DataBinding`给去除掉或者来一个没有`DataBinding`的版本

**Comment by azhon** [comment]
> 建议把`DataBinding`给去除掉或者来一个没有`DataBinding`的版本

为啥？

**Comment by songsongtao** [comment]
DataBinding代码阅读性差，不易维护调试，没事还build错误自动生成类错误

**Comment by azhon** [comment]
> DataBinding代码阅读性差，不易维护调试，没事还build错误自动生成类错误
可以，有时间我拉个分支

**Comment by azhon** [comment]
> DataBinding代码阅读性差，不易维护调试，没事还build错误自动生成类错误

已经抽了一版没有dataBinding的代码
