### ISSUE TITLE
recyclerview中设置点击事件找不到方法

### ISSUE THREAD

**Issue by Jeffery336699** [azhon/TODO-MVVM#6]
![image](https://user-images.githubusercontent.com/16848549/68915271-33964480-079c-11ea-8af1-fa5272486c18.png)

![image](https://user-images.githubusercontent.com/16848549/68915318-77894980-079c-11ea-9a04-2b8d3fb0b0d5.png)

结果：
![image](https://user-images.githubusercontent.com/16848549/68915350-a0a9da00-079c-11ea-91b7-72f0bc32bc84.png)
请求大佬看下

**Comment by azhon** [comment]
去掉方法的static试试

**Comment by Jeffery336699** [comment]
也没用，我试过

**Comment by azhon** [comment]
你网上找找关于databinding这样的写法

**Comment by Jeffery336699** [comment]
嗯嗯，我也是对着你的demo刚看刚学

**Comment by Jeffery336699** [comment]
老铁，感觉你这demo抄着google的

**Comment by azhon** [comment]
> 老铁，感觉你这demo抄着google的

base这些难道也是抄的？

**Comment by Jeffery336699** [comment]
封装确实不错，还是有很多值得学习的地方
