### ISSUE TITLE
多请求中间报错再次重试问题？

### ISSUE THREAD

**Issue by sayyanfu** [azhon/TODO-MVVM#8]
我一个登录有多的请求，输入错误的号中间有一个角色接口请求会出现问题。请求new Consumer<Throwable>()会收到消息。 下次输入正确的号，这个接口就不会往下执行了。

**Comment by azhon** [comment]
没懂，这应该是你自己的业务逻辑处理问题

**Comment by sayyanfu** [comment]
感觉好像是，rxjava的错。

**Comment by sayyanfu** [comment]
/**
     * 请求登录接口
     */
    public void doLogin(String userName, String pwd) {
        showDialog.setValue(true, "登录中...");
        LoginRequest request = new LoginRequest();
        request.setUsername(userName);
        request.setPassword(pwd);
        Gson gson = new Gson();
        String route = gson.toJson(request);
        RequestBody body = RequestBody.create(MediaType.parse("application/json"), route);
        Disposable disposable = Api.getInstance().doLogin(body)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<LoginBean>() {
                    @Override
                    public void accept(LoginBean loginBean) throws Exception {
//                        showDialog.setValue(false);
                        if (HttpsRequestCodeUtils.dologinError(loginBean.getStatus())) {
                            showDialog.setValue(false);
                            error.setValue(loginBean.getMessage());
                            return;
                        }
                        
                        mLoginBean.setValue(loginBean);
                    }
                }, new Consumer<Throwable>() {
                    @Override
                    public void accept(Throwable throwable) throws Exception {
                        showDialog.setValue(false);
                        String message = HttpsRequestCodeUtils.doHttpError(throwable.getMessage());
                        error.setValue(message);
                    }
                });
        addDisposable(disposable);
    }
    
    /**
     * 提交设备信息接口
     */
    public void submitDeviceInfo(String useId, String deviceId, String deviceFactory) {
        showDialog.setValue(true, "登录中...");
        AppInfoRequest request = new AppInfoRequest();
        request.setUsername(useId);
        request.setDevid(deviceId);
        request.setManufacturer(deviceFactory);
        Gson gson = new Gson();
        String route = gson.toJson(request);
        RequestBody body = RequestBody.create(MediaType.parse("application/json"), route);
        Disposable disposable = Api.getInstance().commitAppInfo(body).subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<AppInfoBean>() {
                    @Override
                    public void accept(AppInfoBean appInfoBean) throws Exception {
//                        showDialog.setValue(false);
                        if (HttpsRequestCodeUtils.doTokenError(appInfoBean.getStatus())) {
                            showDialog.setValue(false);
                            EventBus.getDefault().post(new MessageEvent(MessageEvent.TYPE_TOKEN_BE_OVERDUE));
                            error.setValue(appInfoBean.getMessage());
                            return;
                        }
                        mSubmitUserIdBean.setValue(appInfoBean);
                    }
                }, new Consumer<Throwable>() {
                    @Override
                    public void accept(Throwable throwable) throws Exception {
                        showDialog.setValue(false);
                        String message = HttpsRequestCodeUtils.doHttpError(throwable.getMessage());
                        error.setValue(message);
                    }
                });
        addDisposable(disposable);
    }
    
    /**
     * 获取用户角色信息接口
     */
    public void getUserRoleInfo(String useId) {
        showDialog.setValue(true, "登录中...");
        Disposable disposable = Api.getInstance().getRoleInfo(useId).subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<RoleInfoBean>() {
                    @Override
                    public void accept(RoleInfoBean roleInfoBean) throws Exception {
                        if (SPUtils.getInstance().getString(Constants.SP_USER_ROLE).equals("管理员")){
                        }
                        if (HttpsRequestCodeUtils.doTokenError(roleInfoBean.getStatus())) {
                            showDialog.setValue(false);
                            EventBus.getDefault().post(new MessageEvent(MessageEvent.TYPE_TOKEN_BE_OVERDUE));
                            error.setValue(roleInfoBean.getMessage());
                            return;
                        }
                        mUserInfoBean.setValue(roleInfoBean);
                        
                    }
                }, new Consumer<Throwable>() {
                    @Override
                    public void accept(Throwable throwable) throws Exception {
                        showDialog.setValue(false);
                        String message = HttpsRequestCodeUtils.doHttpError(throwable.getMessage());
                        error.setValue(message);
                    }
                });
        addDisposable(disposable);
    }
我在Activity里面挨个调取
viewModel.getSubmitUserIdBean().observe(this, new Observer<AppInfoBean>() {
            @Override
            public void onChanged(AppInfoBean appInfoBean) {
                viewModel.getUserRoleInfo(SPUtils.getInstance().getString(Constants.SP_USER_CODE));
                /*PushAgent.getInstance(context).addAlias(SPUtils.getInstance().getString(Constants.SP_USER_CODE), "user", new UTrack.ICallBack() {
                    @Override
                    public void onMessage(boolean isSuccess, String message) {
                        Toast.makeText(context, message, Toast.LENGTH_SHORT).show();
                    }
                });*/
            }
中间有个接口串两外一个角色返回json错误了，下次登录正常的角色返回正常的json，但是对应的observe的onChanged不再往下执行，必须杀进程。
