### ISSUE TITLE
ERROR: This version of Android Studio cannot open this project, please retry with Android Studio 3.6 or newer.

### ISSUE THREAD

**Issue by levilevichen** [azhon/TODO-MVVM#9]
ERROR: This version of Android Studio cannot open this project, please retry with Android Studio 3.6 or newer.

**Comment by azhon** [comment]
使用AS3.6及以上版本打开此项目------------------ 原始邮件 ------------------
发件人: "levilevichen"<notifications@github.com>
发送时间: 2020年1月28日(星期二) 上午10:40
收件人: "azhon/TODO-MVVM"<TODO-MVVM@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [azhon/TODO-MVVM] ERROR: This version of Android Studio cannot openthis project, please retry with Android Studio 3.6 or newer. (#9)



ERROR: This version of Android Studio cannot open this project, please retry with Android Studio 3.6 or newer.
 
&mdash;
